title: Sam McIlroy # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Software/Data Engineer</b>
  <br><br>
  Completed a combined MSc programme in data science and software engineering at Birkbeck, University of London 
  (MSc Data Science). Focused study and final project on data engineering, distributed and cloud technologies. 
  <br><br>
  Professional experience in ETL, database and business intelligence development.
  <br><br>
  Seeking DE/SWE roles, especially within the technology sector.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
