title: Sam McIlroy # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Data Engineer</b>
  <br><br>
  Data Engineer with several years experience in data and business intelligence development roles. 
  Recently completed a combined MSc programme in data science and software engineering at Birkbeck, 
  University of London (MSc Data Science). Focused study and final project on data engineering,
  distributed and cloud technologies.
  <br><br>
  Seeking DE/SWE roles, especially within the technology sector.
  <br><br>
  <a href="https://www.linkedin.com/in/sam-mcilroy-4484579a/">View My LinkedIn Profile</a>
  <br><br>
  <a href="/Sam_McIlroy_CV.pdf">View My CV</a>
theme: jekyll-theme-minimal
